@extends('layouts.layout')
@section('title')
    Voy a modernizar mi empresa || Technomundo HMR@endsection
@endsection
@section('content')
<header>
    @include('main.logoHeader')
</header>
<section class="sticky-top bg-white">
    @include('main.navbar')
</section>
<section>
    @include('main.software1')
</section>
<section>
    @include('main.software2')
</section>
<section>
    @include('main.software4')
</section>  
<br>
<section>
    @include('main.software3')
</section>
<section>
    @include('main.software4')
</section>
<br>
<footer>
    @include('layouts.footer')
    @include('cms.footer')
</footer>
@endsection